excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ronaldojr.github.io
title: Vulgo Xablau
tagline: Dev mas não teme
description: Compartilhando conhecimentos e bobagens
paginate: 5
